### ISSUE TITLE
Installing requirements

### ISSUE THREAD

**Issue by janrvdolf** [AHAPX/websocket#2]
Hi, I have a problem installing requirements with Python 3.6.8: 

```
Collecting git+https://github.com/AHAPX/subscriber.git (from -r requirements.txt (line 3))
  Cloning https://github.com/AHAPX/subscriber.git to /tmp/pip-req-build-v_0rjeos
  Running command git clone -q https://github.com/AHAPX/subscriber.git /tmp/pip-req-build-v_0rjeos
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-v_0rjeos/setup.py", line 2, in <module>
        from pip.req import parse_requirements
    ModuleNotFoundError: No module named 'pip.req'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-v_0rjeos/
```

How can I fix it? Thank you.

**Comment by janrvdolf** [comment]
Ok, I was using too new Python. I should have used Python 3.4. You can close it.
